export const areaCheckBox = [
    {
        id: 101,
        type: 'checkbox',
        checked: true,
        item: '0,63',
    },
    {
        id: 102,
        type: 'checkbox',
        checked: true,
        item: '0,90',
    },
    {
        id: 103,
        type: 'checkbox',
        checked: true,
        item: '1,13',
    },
    {
        id: 104,
        type: 'checkbox',
        checked: true,
        item: '1,56',
    },
    {
        id: 105,
        type: 'checkbox',
        checked: true,
        item: '2,56',
    },
    {
        id: 106,
        type: 'checkbox',
        checked: true,
        item: '2,88',
    },
];

export const itemsCheckBox = [
    {
        id: 11,
        type: 'checkbox',
        checked: true,
        item: 'Пустой номер',
    },
    {
        id: 12,
        type: 'checkbox',
        checked: true,
        item: 'Лежак',
    },
    {
        id: 13,
        type: 'checkbox',
        checked: true,
        item: 'Когтеточка',
    },
    {
        id: 14,
        type: 'checkbox',
        checked: true,
        item: 'Игровой-комплекс',
    },
    {
        id: 15,
        type: 'checkbox',
        checked: true,
        item: 'Домик',
    },

];
export const cards = [
    {
        id: 1,
        picture: 'images/Economy.png',
        name: 'Эконом',
        size: '90х70х100',
        area: '0,63',
        items: 'Пустой номер',
        images: ['NoItems.svg'],
        price: '100',
    },
    {
        id: 2,
        picture: 'images/EconomyPlus.png',
        name: 'Эконом плюс',
        size: '90х100х180',
        area: '0,90',
        items: 'Лежак Когтеточка',
        images: ['bed.svg','scratchingPost.svg'],
        price: '200',
    },
    {
        id: 3,
        picture: 'images/Comfort.png',
        name: 'Комфорт',
        size: '100х125х180',
        area: '1,13',
        items: 'Лежак Когтеточка Игровой-комплекс',
        images: ['bed.svg','scratchingPost.svg','toys.svg'],
        price: '250',
    },
    {
        id: 4,
        picture: 'images/Suit.png',
        name: 'Сьют',
        size: '125х125х180',
        area: '1,56',
        items: 'Лежак Когтеточка Игровой-комплекс',
        images: ['bed.svg','scratchingPost.svg','toys.svg'],
        price: '350',
    },
    {
        id: 5,
        picture: 'images/Luxe.png',
        name: 'Люкс',
        size: '160х160х180',
        area: '2,56',
        items: 'Лежак Когтеточка Игровой-комплекс Домик',
        images: ['bed.svg','scratchingPost.svg','toys.svg','home.svg'],
        price: '500',
    },
    {
        id: 6,
        picture: 'images/SuperLuxe.png',
        name: 'Супер-Люкс',
        size: '180х160х180',
        area: '2,88',
        items: 'Лежак Когтеточка Игровой-комплекс Домик',
        images: ['bed.svg','scratchingPost.svg','toys.svg','home.svg'],
        price: '600',
    },
];

